/**
 * components/revision/stages/ConnectDotsStage.jsx
 * Stage 4 – Concept mapping timeline dynamically generated by Gemini.
 */

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Network, ArrowRight, Loader2 } from 'lucide-react';
import Button from '../../ui/Button';
import QuestionCinematic from '../shared/QuestionCinematic';
import { generateStageQuestion } from '../../../api/gemini';

const ConnectDotsStage = ({ onComplete, apiKey, topic }) => {
  const [cinematicDone, setCinematicDone] = useState(false);
  const [step, setStep] = useState(0); // 0: question, 1: incorrect retry, 2: correct timeline
  const [loading, setLoading] = useState(true);
  const [puzzleData, setPuzzleData] = useState(null);

  const topicName = topic?.title || 'General Web Development';

  // Fallbacks in case Gemini rate limits or fails
  const getFallbackData = () => {
    const titleLower = topicName.toLowerCase();
    
    // Fallback 1: Closures / Scope
    if (titleLower.includes('closure') || titleLower.includes('scope')) {
      return {
        question: "Closures allow functions to retain state. But do you remember what fundamental JS concept makes this possible?",
        options: [
          "Lexical Scope and Execution Contexts",
          "Asynchronous Event Loops"
        ],
        correctIndex: 0,
        timeline: [
          { label: "Execution Contexts", desc: "Whenever a function is invoked, a fresh context is created." },
          { label: "Lexical Scope", desc: "Inner functions have static access to outer function variables." },
          { label: "Closures", desc: "A function packaged with references to its surrounding state." },
          { label: "Data Hiding", desc: "Enables private variables that cannot be altered from global scope." }
        ]
      };
    }

    // Fallback 2: Default Promises / Async
    return {
      question: "You know Promises well. But do you remember WHY they exist?",
      options: [
        "To replace async/await chains",
        "Because callbacks became too messy (Callback Hell)"
      ],
      correctIndex: 1,
      timeline: [
        { label: "Callbacks", desc: "The original way to handle async JS." },
        { label: "Callback Hell", desc: "Nesting became unreadable and messy." },
        { label: "Promises", desc: "Introduced .then() and .catch() chains." },
        { label: "Async/Await", desc: "Cleaner syntax looking like synchronous code." }
      ]
    };
  };

  useEffect(() => {
    const fetchTimeline = async () => {
      try {
        const data = await generateStageQuestion(apiKey, topic, 'connect_dots');
        if (data && data.question && data.timeline && data.options) {
          setPuzzleData(data);
        } else {
          throw new Error('Incomplete puzzle schema from Gemini');
        }
      } catch (err) {
        console.warn("Gemini connection puzzle generation failed, using local context fallback:", err);
        setPuzzleData(getFallbackData());
      } finally {
        setLoading(false);
      }
    };
    fetchTimeline();
  }, [apiKey, topic]);

  const handleSelectOption = (index) => {
    if (index === puzzleData.correctIndex) {
      setStep(2);
    } else {
      setStep(1);
    }
  };

  if (loading) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-indigo-400 gap-4 py-16">
        <Loader2 size={40} className="animate-spin" />
        <p className="animate-pulse">Gemini is mapping concept relations for {topicName}...</p>
        <img 
          src="/ninja.gif" 
          alt="Loading animation" 
          className="w-48 h-48 object-contain drop-shadow-[0_0_15px_rgba(255,255,255,0.15)] mt-2"
        />
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, x: 50 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -50 }}
      className="max-w-2xl mx-auto w-full flex flex-col gap-6 py-4"
    >
      <div className="text-center shrink-0">
        <div className="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-indigo-500/20 text-indigo-400 mb-3">
          <Network size={24} />
        </div>
        <h2 className="text-2xl font-bold text-white">Connect the Dots</h2>
        <p className="text-dark-400 text-sm mt-1">See the big picture for {topicName}.</p>
      </div>

      <QuestionCinematic
        question={puzzleData.question}
        subtext="Conceptual Thinking"
        accentColor="indigo"
        onReady={() => setCinematicDone(true)}
      />

      {cinematicDone && (
        <motion.div
          className="glass-card p-6 md:p-10 text-center"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          {step === 0 && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
              <div className="space-y-3 max-w-sm mx-auto">
                {puzzleData.options.map((opt, idx) => (
                  <button 
                    key={idx}
                    onClick={() => handleSelectOption(idx)} 
                    className="w-full p-4 rounded-xl bg-dark-900 border border-dark-700/60 hover:border-indigo-500/50 hover:bg-dark-800 transition-colors text-sm text-dark-200 text-left font-medium"
                  >
                    {opt}
                  </button>
                ))}
              </div>
            </motion.div>
          )}

          {step === 1 && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
              <p className="text-red-400 mb-4 font-semibold">Not quite. That doesn't capture the relationship correctly!</p>
              <Button onClick={() => setStep(0)} variant="primary">Try Again</Button>
            </motion.div>
          )}

          {step === 2 && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex flex-col items-center">
              <p className="text-green-400 font-bold mb-6">Exactly! Let's map out the concept path:</p>
              <div className="flex flex-col items-center gap-2 mb-8 w-full max-w-sm">
                {puzzleData.timeline.map((item, idx) => (
                  <motion.div 
                    key={idx} 
                    initial={{ opacity: 0, y: 10 }} 
                    animate={{ opacity: 1, y: 0 }} 
                    transition={{ delay: idx * 0.4 }} 
                    className="w-full"
                  >
                    <div className="p-4 bg-dark-900/55 border border-indigo-500/30 rounded-xl">
                      <p className="font-bold text-indigo-300 text-sm">{item.label}</p>
                      <p className="text-xs text-dark-400 mt-1">{item.desc}</p>
                    </div>
                    {idx < puzzleData.timeline.length - 1 && (
                      <div className="flex justify-center my-2">
                        <ArrowRight size={16} className="text-dark-600 rotate-90" />
                      </div>
                    )}
                  </motion.div>
                ))}
              </div>
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 2 }}>
                <Button variant="primary" onClick={onComplete}>Continue</Button>
              </motion.div>
            </motion.div>
          )}
        </motion.div>
      )}
    </motion.div>
  );
};

export default ConnectDotsStage;
